version: '3'
services:
  db_outdoor:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web_outdoor:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db_outdoor
